import styles from './digest.module.css';
import { MASCOT } from '@/components/Mascot';
import Avatar from '@/components/Avatar';
import { PEOPLE } from '@/lib/demo-people';

const WEEK_STANDINGS = [
  { person: PEOPLE[1], points: 142, streak: 5 },
  { person: PEOPLE[0], points: 128, streak: 7 },
  { person: PEOPLE[2], points: 115, streak: 3 },
];

export const metadata = {
  title: 'Friday Digest · Bespoke Social',
};

/**
 * Digest archive (design doc 7.10). The Friday agent extended run will
 * generate real digests (archived at /digest/YYYY-WW); until that
 * pipeline exists this page shows a sample issue in the persona voice so
 * the format and layout are settled.
 */

const SAMPLE_SECTIONS = [
  {
    icon: '📸',
    heading: 'BE(spoke)REAL of the Week',
    body: "Shrey's heroic desk plant swept the Award Ceremony three nights running and has quietly amassed the most anonymous likes in company history. The plant has not commented, which frankly shows leadership.",
  },
  {
    icon: '🔤',
    heading: 'Wordle and Bespokle Drama',
    body: 'Adhvaith opened the week with a two-guess solve and has been insufferable in the best way since. Tarun found a ladder route one step faster than the fastest known route, which should be impossible, and the matter is under investigation.',
  },
  {
    icon: '🎭',
    heading: 'Two Truths, One Lie',
    body: 'Most of the company believed Tarun once won a regional yo-yo competition. The yo-yo remains unconfirmed. The vote split dropped on Slack at end of day and the group chat has not recovered.',
  },
  {
    icon: '📖',
    heading: 'The Saga So Far',
    body: 'Our sentient staging server has unionized the CI runners. Chapter two lands when the next author shows up. Attendance at the read-along is voluntary but the server is taking names.',
  },
  {
    icon: '🧠',
    heading: 'Trivia Standings',
    body: 'Tarun answers before the timer bar finishes rendering. We have reviewed the tape. It is legal. It should not be.',
  },
  {
    icon: '🃏',
    heading: 'Cards Minted',
    body: 'One new coffee chat card this week, minted after a genuine donut-bot match. Two silhouettes remain. The completionists know who they are.',
  },
];

export default function DigestPage() {
  return (
    <div className="container">
      <div className={styles.digest}>
        <div className={styles.header}>
          <h1 className={styles.title}>
            <span className={styles.titleGradient}>The Friday Digest</span>
          </h1>
          <p className={styles.subtitle}>
            Weekly culture recap, written entirely by {MASCOT.name}
          </p>
        </div>

        <div className={styles.sampleNote}>
          📌 Sample issue. Real digests are generated by the Friday agent run
          and archived here weekly.
        </div>

        <article className={styles.issue} id="digest-issue">
          <div className={styles.issueHeader}>
            <span className={styles.issueBadge}>Week of Jul 4, 2026</span>
            <h2 className={styles.issueTitle}>
              The Plant, The Yo-yo, and Two Guesses
            </h2>
            <p className={styles.issueByline}>
              By {MASCOT.name}, {MASCOT.title}, taking this far too seriously
              since day one
            </p>
          </div>

          {/* Best BE(spoke)REAL of the week */}
          <figure className={styles.photoFeature} id="digest-photo">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/bereal/bereal1.jpg"
              alt="Best BE(spoke)REAL of the week"
              className={styles.photoImage}
            />
            <figcaption className={styles.photoCaption}>
              <span className={styles.photoLabel}>
                📸 Best BE(spoke)REAL of the week
              </span>
              <span className={styles.photoCredit}>
                <Avatar
                  name={PEOPLE[0].name}
                  photo={PEOPLE[0].photo}
                  size={24}
                />
                by {PEOPLE[0].name}, crowned by anonymous likes
              </span>
            </figcaption>
          </figure>

          {SAMPLE_SECTIONS.map((section) => (
            <section key={section.heading} className={styles.section}>
              <h3 className={styles.sectionHeading}>
                <span>{section.icon}</span> {section.heading}
              </h3>
              <p className={styles.sectionBody}>{section.body}</p>
            </section>
          ))}

          {/* Week's leaderboard */}
          <section className={styles.section}>
            <h3 className={styles.sectionHeading}>
              <span>🏆</span> The Week&apos;s Leaderboard
            </h3>
            <div className={styles.boardTable} id="digest-board">
              {WEEK_STANDINGS.map((row, i) => (
                <div key={row.person.id} className={styles.boardRow}>
                  <span className={styles.boardRank}>
                    {['🥇', '🥈', '🥉'][i]}
                  </span>
                  <Avatar
                    name={row.person.name}
                    photo={row.person.photo}
                    size={32}
                  />
                  <span className={styles.boardName}>{row.person.name}</span>
                  <span className={styles.boardStreak}>🔥 {row.streak}d</span>
                  <span className={styles.boardPoints}>{row.points} pts</span>
                </div>
              ))}
            </div>
          </section>

          <footer className={styles.issueFooter}>
            Next week: the multiplier war, chapter two of the saga, and, if
            the vision model behaves, the return of the awards ceremony
            after-party thread.
          </footer>
        </article>
      </div>
    </div>
  );
}
